#
# SPDX-License-Identifier: Apache-2.0
#
---
trigger:
  branches:
    include:
      - "*"
  tags:
    include:
      - "*"

pool:
  vmImage: "ubuntu-latest"

variables:
  DISPLAY: :99.0

steps:
  - script: nohup Xvfb :99 -screen 0 1024x768x24 < /dev/null > /dev/null 2>&1 &
    displayName: Start Xvfb
  - task: NodeTool@0
    inputs:
      versionSpec: '12.x'
    displayName: Use Node.js 12.x
  - script: npm install -g vsce
    displayName: Install Visual Studio Code Extensions CLI
  - script: npm ci
    displayName: Install extension dependencies
  - script: npm audit
    displayName: Audit extension dependencies
  - script: npm test
    displayName: Run extension tests
  - script: vsce package
    displayName: Package extension